highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Marufa Akhter's Resume
name: Marufa Akhter
email: marufaripa.mr@gmail.com
email_full: mailto:marufaripa.mr@gmail.com
website: github.io/MarufaAkhter
website_full: https://github.com/MarufaAkhter
github: trending
twitter: twitter
tel: +46 736430829
tel_full: tel:+46736430829
google_maps: 
address:
  street: Flogstavagen
  postcode: 75272
  city: Uppsala
  country: Sweden
  
google_analytics: UA-69300817-1
# needed for travis-ci build
exclude: [vendor]
